version: "3.8"

services:
  server:
    image: node:12.16-alpine
    command: sh -c "yarn && yarn knex migrate:latest && yarn start:dev"
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - nest-starter-network
  db:
    image: postgres
    networks:
      - nest-starter-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  pgdata:
networks:
  nest-starter-network:

    # docker network create nest-starter-network
    # network- nest-starter-network
    # db alias - postgresDBTest
    # docker run -d \
    #     --network nest-starter-network --network-alias postgresDBTest \
    #     -v nest-postgres-data:/var/lib/postgresql \
    #     -e POSTGRES_PASSWORD=postgres \
    #     -e POSTGRES_USER=postgres \
    #     -e POSTGRES_DB=nest-starter-db-test \
    #     postgres

    # docker run -dp 3333:3333 \
    # -w /app -v "$(pwd):/app" \
    # --network nest-starter-network \
    # -e NODE_ENV=development \
    # -e DB_HOST=postgresDBTest \
    # -e DB_PORT=5432 \
    # -e DB_NAME=nest-starter-db-test \
    # -e DB_USER=postgres \
    # -e DB_PASSWORD=postgres \
    # -e APP_PORT=3333 \
    # -e JWT_SECRET=JWT_SECRET \
    # -e JWT_EXPIRES_IN=2h \
    # -e JWT_REFRESH=JWT_REFRESH \
    # -e JWT_REFRESH_EXPIRES_IN=7d \
    # -e BASE_FRONTEND_URL=http://localhost:3000 \
    # node:12-alpine \
    # sh -c "yarn && yarn knex migrate:latest && yarn start:dev"


    # docker run -d \
    # --network nest-starter-network --network-alias mysql \
    # -v nest-mysql-data:/var/lib/mysql \
    # -e MYSQL_ROOT_PASSWORD=secret \
    # -e MYSQL_DATABASE=todos \
    # mysql:5.7

    #     docker run -dp 3333:3333 \
    # -w /app -v "$(pwd):/app" \
    # --network nest-starter-network \
    # -e NODE_ENV=development \
    # -e DB_HOST=postgresDBTest \
    # -e DB_PORT=3306 \
    # -e DB_NAME=todos \
    # -e DB_USER=root \
    # -e DB_PASSWORD=secret \
    # -e APP_PORT=3333 \
    # -e JWT_SECRET=JWT_SECRET \
    # -e JWT_EXPIRES_IN=2h \
    # -e JWT_REFRESH=JWT_REFRESH \
    # -e JWT_REFRESH_EXPIRES_IN=7d \
    # -e BASE_FRONTEND_URL=http://localhost:3000 \
    # node:12.16-alpine \
    # sh -c "yarn && yarn knex migrate:latest && yarn start:dev"
